"use server";
import {revalidatePath} from "next/cache";
import {z} from "zod";
import {requireOrganizationPermission} from "@/lib/auth/session";
import {createClient} from "@/lib/supabase/server";
const name=z.string().trim().min(1).max(180);
export async function createDepartment(fd:FormData){const {organizationId}=await requireOrganizationPermission("department.manage");const s=await createClient();const v=z.object({name,description:z.string().trim().max(500).optional(),health:z.string().trim().max(60).optional(),readiness:z.coerce.number().min(0).max(100).optional()}).parse(Object.fromEntries(fd));const {error}=await s.from("departments").insert({...v,organization_id:organizationId,verification_status:"sample_unapproved",metadata:{classification:"SAMPLE / UNAPPROVED"}});if(error)throw new Error(error.message);revalidatePath("/departments");revalidatePath("/");}
export async function updateDepartment(fd:FormData){const {organizationId}=await requireOrganizationPermission("department.manage");const s=await createClient();const v=z.object({id:z.string().uuid(),health:z.string().trim().max(60),readiness:z.coerce.number().min(0).max(100),status:z.enum(["draft","active","archived"])}).parse(Object.fromEntries(fd));const {error}=await s.from("departments").update({health:v.health,readiness:v.readiness,status:v.status}).eq("id",v.id).eq("organization_id",organizationId);if(error)throw new Error(error.message);revalidatePath("/departments");revalidatePath("/");}
export async function createTask(fd:FormData){const {user,organizationId}=await requireOrganizationPermission("task.manage_department");const s=await createClient();const v=z.object({title:name,description:z.string().trim().max(1000).optional(),department_id:z.string().uuid(),priority:z.enum(["low","medium","high","critical"]),due_at:z.string().optional()}).parse(Object.fromEntries(fd));const {error}=await s.from("tasks").insert({...v,due_at:v.due_at||null,organization_id:organizationId,created_by:user.id,updated_by:user.id,verification_status:"sample_unapproved",visibility:"department"});if(error)throw new Error(error.message);revalidatePath("/tasks");revalidatePath("/");}
export async function updateTask(fd:FormData){const {user,organizationId}=await requireOrganizationPermission("task.read");const s=await createClient();const v=z.object({id:z.string().uuid(),status:z.enum(["backlog","planned","in_progress","blocked","completed","archived"]),progress:z.coerce.number().int().min(0).max(100),priority:z.enum(["low","medium","high","critical"])}).parse(Object.fromEntries(fd));const {error}=await s.from("tasks").update({...v,updated_by:user.id,archived_at:v.status==="archived"?new Date().toISOString():null}).eq("id",v.id).eq("organization_id",organizationId);if(error)throw new Error(error.message);revalidatePath("/tasks");revalidatePath("/");}
export async function addTaskComment(fd:FormData){const {user,organizationId}=await requireOrganizationPermission("task.read");const s=await createClient();const v=z.object({task_id:z.string().uuid(),body:z.string().trim().min(1).max(2000)}).parse(Object.fromEntries(fd));const {error}=await s.from("comments").insert({organization_id:organizationId,target_type:"task",target_id:v.task_id,body:v.body,author_id:user.id,visibility:"department"});if(error)throw new Error(error.message);revalidatePath("/tasks");}
export async function assignTask(fd:FormData){const {user,organizationId}=await requireOrganizationPermission("task.assign");const s=await createClient();const v=z.object({task_id:z.string().uuid(),organization_member_id:z.string().uuid()}).parse(Object.fromEntries(fd));const [{data:task},{data:member}]=await Promise.all([s.from("tasks").select("id").eq("id",v.task_id).eq("organization_id",organizationId).maybeSingle(),s.from("organization_members").select("id").eq("id",v.organization_member_id).eq("organization_id",organizationId).eq("status","active").maybeSingle()]);if(!task||!member)throw new Error("Task assignment scope validation failed.");const {error}=await s.from("task_assignees").upsert({task_id:task.id,organization_member_id:member.id,assigned_by:user.id});if(error)throw new Error(error.message);revalidatePath("/tasks");}
export async function createReport(fd:FormData){const {user,organizationId}=await requireOrganizationPermission("report.submit");const s=await createClient();const v=z.object({report_period_id:z.string().uuid(),department_id:z.string().uuid(),health:name,summary:z.string().trim().min(1).max(3000),progress_wins:z.string().trim().max(3000).optional(),blockers:z.string().trim().max(3000).optional(),leadership_request:z.string().trim().max(3000).optional()}).parse(Object.fromEntries(fd));const {error}=await s.from("reports").insert({...v,organization_id:organizationId,reporter_id:user.id,status:"submitted",verification_status:"sample_unapproved",visibility:"department"});if(error)throw new Error(error.message);revalidatePath("/reports");revalidatePath("/");}
export async function reviewReport(fd:FormData){const {user,organizationId}=await requireOrganizationPermission("report.review");const s=await createClient();const v=z.object({id:z.string().uuid(),review_state:z.enum(["in_review","changes_requested","accepted"]),review_comments:z.string().trim().max(3000).optional()}).parse(Object.fromEntries(fd));const {error}=await s.from("reports").update({...v,reviewer_id:user.id,reviewed_at:new Date().toISOString(),status:v.review_state==="accepted"?"accepted":"submitted"}).eq("id",v.id).eq("organization_id",organizationId);if(error)throw new Error(error.message);revalidatePath("/reports");revalidatePath("/");}
