"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requireOrganizationPermission } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
const text=z.string().trim().min(1).max(120);
async function authorized(permission:string){const context=await requireOrganizationPermission(permission);return {...context,supabase:await createClient()};}
export async function updateOrganization(formData:FormData){const {organizationId,supabase}=await authorized("organization.manage");const input=z.object({name:text,status:z.enum(["draft","active","archived"])}).parse(Object.fromEntries(formData));const {error}=await supabase.from("organizations").update(input).eq("id",organizationId);if(error)throw new Error(`Organization update failed: ${error.message}`);revalidatePath("/administration");}
export async function createProvisioningRequest(formData:FormData){const {user,organizationId,supabase}=await authorized("user.provision");const input=z.object({email:z.string().trim().email().max(254),display_name:text.optional().or(z.literal("")),requested_role_id:z.string().uuid().optional().or(z.literal(""))}).parse(Object.fromEntries(formData));const {error}=await supabase.from("user_provisioning_requests").insert({organization_id:organizationId,email:input.email.toLowerCase(),display_name:input.display_name||null,requested_role_id:input.requested_role_id||null,requested_by:user.id});if(error)throw new Error(`Provisioning request failed: ${error.message}`);revalidatePath("/administration");}
export async function setMembershipStatus(formData:FormData){const {organizationId,supabase}=await authorized("membership.manage");const input=z.object({membership_id:z.string().uuid(),status:z.enum(["draft","active","archived"])}).parse(Object.fromEntries(formData));const {error}=await supabase.from("organization_members").update({status:input.status}).eq("id",input.membership_id).eq("organization_id",organizationId);if(error)throw new Error(`Membership update failed: ${error.message}`);revalidatePath("/administration");}
export async function createRole(formData:FormData){const {organizationId,supabase}=await authorized("role.manage");const input=z.object({key:z.string().trim().regex(/^[a-z0-9_]+$/).max(60),name:text,description:z.string().trim().max(300).optional()}).parse(Object.fromEntries(formData));const {error}=await supabase.from("roles").insert({organization_id:organizationId,...input,is_system:false});if(error)throw new Error(`Role creation failed: ${error.message}`);revalidatePath("/administration");}
export async function assignRole(formData:FormData){const {user,organizationId,supabase}=await authorized("role.manage");const input=z.object({membership_id:z.string().uuid(),role_id:z.string().uuid()}).parse(Object.fromEntries(formData));const [{data:member},{data:role}]=await Promise.all([supabase.from("organization_members").select("id").eq("id",input.membership_id).eq("organization_id",organizationId).maybeSingle(),supabase.from("roles").select("id").eq("id",input.role_id).eq("organization_id",organizationId).maybeSingle()]);if(!member||!role)throw new Error("Role assignment scope validation failed.");const {error}=await supabase.from("member_roles").upsert({organization_member_id:member.id,role_id:role.id,granted_by:user.id});if(error)throw new Error(`Role assignment failed: ${error.message}`);revalidatePath("/administration");}
export async function assignCapability(formData:FormData){const {organizationId,supabase}=await authorized("role.manage");const input=z.object({role_id:z.string().uuid(),permission_id:z.string().uuid()}).parse(Object.fromEntries(formData));const {data:role}=await supabase.from("roles").select("id,is_system").eq("id",input.role_id).eq("organization_id",organizationId).maybeSingle();if(!role||role.is_system)throw new Error("Only organization-owned custom roles can be changed.");const {error}=await supabase.from("role_permissions").upsert({role_id:role.id,permission_id:input.permission_id});if(error)throw new Error(`Capability assignment failed: ${error.message}`);revalidatePath("/administration");}
