-- Phase 2D controlled importer. Prototype-derived data remains SAMPLE / UNAPPROVED.
insert into public.permissions(key,description) values('import.manage','Create and reconcile controlled import previews'),('import.execute','Confirm and execute transactional imports') on conflict(key) do nothing;
create table public.import_batches(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,
 filename text not null,source_digest text not null check(source_digest~'^[0-9a-f]{64}$'),source_type text not null default 'aftifestCommandData',schema_version text not null,
 raw_payload text not null,preview jsonb not null default '{}'::jsonb,record_counts jsonb not null default '{}'::jsonb,warnings jsonb not null default '[]'::jsonb,
 status text not null default 'uploaded' check(status in('uploaded','validated','ready','importing','completed','failed','rolled_back')),
 uploaded_by uuid not null references public.profiles(id),confirmed_by uuid references public.profiles(id),uploaded_at timestamptz not null default now(),confirmed_at timestamptz,completed_at timestamptz,
 imported_counts jsonb not null default '{}'::jsonb,failure_reason text,correlation_id uuid not null default gen_random_uuid(),unique(organization_id,source_digest));
create table public.import_items(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,batch_id uuid not null references public.import_batches(id) on delete cascade,
 source_type text not null,source_record_key text not null,target_type text not null,source_payload jsonb not null,mapping jsonb not null default '{}'::jsonb,
 reconciliation_status text not null default 'ready' check(reconciliation_status in('ready','excluded','deferred','imported','failed')),
 reconciliation_notes text,target_id uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(batch_id,source_type,source_record_key));
create table public.import_person_mappings(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,batch_id uuid not null references public.import_batches(id) on delete cascade,source_name text not null,mapping_status text not null default 'unmapped' check(mapping_status in('unmapped','mapped','deferred')),organization_member_id uuid references public.organization_members(id) on delete restrict,updated_by uuid references public.profiles(id),updated_at timestamptz not null default now(),unique(batch_id,source_name));
alter table public.import_batches enable row level security;alter table public.import_items enable row level security;alter table public.import_person_mappings enable row level security;
create policy import_batches_select on public.import_batches for select to authenticated using(public.has_permission(organization_id,'import.manage'));
create policy import_items_select on public.import_items for select to authenticated using(public.has_permission(organization_id,'import.manage') and exists(select 1 from public.import_batches b where b.id=batch_id));
create policy import_people_select on public.import_person_mappings for select to authenticated using(public.has_permission(organization_id,'import.manage') and exists(select 1 from public.import_batches b where b.id=batch_id));
grant select on public.import_batches,public.import_items,public.import_person_mappings to authenticated;

alter table public.departments add column import_batch_id uuid references public.import_batches(id),add column source_record_key text,add column source_provenance jsonb not null default '{}'::jsonb;
alter table public.tasks add column import_batch_id uuid references public.import_batches(id),add column source_record_key text,add column source_provenance jsonb not null default '{}'::jsonb;
alter table public.reports add column import_batch_id uuid references public.import_batches(id),add column source_record_key text,add column source_provenance jsonb not null default '{}'::jsonb;
alter table public.content_items add column import_batch_id uuid references public.import_batches(id),add column source_record_key text,add column source_provenance jsonb not null default '{}'::jsonb;
alter table public.sponsors add column import_batch_id uuid references public.import_batches(id),add column source_record_key text,add column source_provenance jsonb not null default '{}'::jsonb;
alter table public.milestones add column import_batch_id uuid references public.import_batches(id),add column source_record_key text,add column source_provenance jsonb not null default '{}'::jsonb;
alter table public.decisions add column import_batch_id uuid references public.import_batches(id),add column source_record_key text,add column source_provenance jsonb not null default '{}'::jsonb;
alter table public.resources add column import_batch_id uuid references public.import_batches(id),add column source_record_key text,add column source_provenance jsonb not null default '{}'::jsonb;
create unique index departments_import_source_uq on public.departments(organization_id,import_batch_id,source_record_key) where import_batch_id is not null;
create unique index tasks_import_source_uq on public.tasks(organization_id,import_batch_id,source_record_key) where import_batch_id is not null;
create unique index content_import_source_uq on public.content_items(organization_id,import_batch_id,source_record_key) where import_batch_id is not null;
create unique index sponsors_import_source_uq on public.sponsors(organization_id,import_batch_id,source_record_key) where import_batch_id is not null;
create unique index milestones_import_source_uq on public.milestones(organization_id,import_batch_id,source_record_key) where import_batch_id is not null;
create unique index decisions_import_source_uq on public.decisions(organization_id,import_batch_id,source_record_key) where import_batch_id is not null;
create unique index resources_import_source_uq on public.resources(organization_id,import_batch_id,source_record_key) where import_batch_id is not null;

create or replace function public.create_import_preview(target_organization_id uuid,source_filename text,source_digest text,source_raw_payload text,detected_schema text,preview_data jsonb,item_data jsonb) returns uuid
language plpgsql security definer set search_path=public,extensions,pg_temp as $$
declare batch uuid;actual text;item jsonb;
begin
 if not public.has_permission(target_organization_id,'import.manage') then raise exception 'import preview denied';end if;
 actual:=encode(extensions.digest(convert_to(source_raw_payload,'UTF8'),'sha256'),'hex');if actual<>$3 then raise exception 'source digest mismatch';end if;
 select b.id into batch from public.import_batches b where b.organization_id=target_organization_id and b.source_digest=$3;
 if batch is not null then return batch;end if;
 insert into public.import_batches(organization_id,filename,source_digest,schema_version,raw_payload,preview,record_counts,warnings,status,uploaded_by)
 values(target_organization_id,source_filename,$3,detected_schema,source_raw_payload,preview_data,coalesce(preview_data->'counts','{}'),coalesce(preview_data->'warnings','[]'),'ready',auth.uid()) returning id into batch;
 for item in select * from jsonb_array_elements(item_data) loop
  insert into public.import_items(organization_id,batch_id,source_type,source_record_key,target_type,source_payload,mapping,reconciliation_status,reconciliation_notes)
  values(target_organization_id,batch,item->>'sourceType',item->>'sourceKey',item->>'targetType',item->'payload',coalesce(item->'mapping','{}'),item->>'status',item->>'notes');
 end loop;
 for item in select * from jsonb_array_elements(coalesce(preview_data->'peopleMappings','[]')) loop insert into public.import_person_mappings(organization_id,batch_id,source_name)values(target_organization_id,batch,item->>'name')on conflict do nothing;end loop;return batch;
end$$;

create or replace function public.set_import_item_state(target_item_id uuid,new_state text,notes text default null) returns public.import_items
language plpgsql security definer set search_path=public,pg_temp as $$declare i public.import_items;begin select * into i from public.import_items where id=target_item_id for update;if i.id is null or not public.has_permission(i.organization_id,'import.manage') then raise exception 'import reconciliation denied';end if;if i.reconciliation_status='imported' or new_state not in('ready','excluded','deferred') then raise exception 'invalid reconciliation change';end if;update public.import_items set reconciliation_status=new_state,reconciliation_notes=notes,updated_at=now() where id=i.id returning * into i;return i;end$$;

create or replace function public.set_import_person_mapping(target_mapping_id uuid,new_state text,target_member_id uuid default null)returns public.import_person_mappings language plpgsql security definer set search_path=public,pg_temp as $$declare m public.import_person_mappings;begin select*into m from public.import_person_mappings where id=target_mapping_id for update;if m.id is null or not public.has_permission(m.organization_id,'import.manage')then raise exception'import person mapping denied';end if;if new_state not in('unmapped','mapped','deferred')then raise exception'invalid person mapping state';end if;if new_state='mapped'and(target_member_id is null or not exists(select 1 from public.organization_members where id=target_member_id and organization_id=m.organization_id and status='active'))then raise exception'active organization member mapping required';end if;update public.import_person_mappings set mapping_status=new_state,organization_member_id=case when new_state='mapped'then target_member_id else null end,updated_by=auth.uid(),updated_at=now()where id=m.id returning*into m;return m;end$$;

create or replace function public.execute_import_batch(target_batch_id uuid) returns public.import_batches
language plpgsql security definer set search_path=public,pg_temp as $$
declare b public.import_batches;i public.import_items;target uuid;counts jsonb:='{}';prov jsonb;mapped_member uuid;mapped_profile uuid;person_name text;
begin select * into b from public.import_batches where id=target_batch_id for update;if b.id is null or not public.has_permission(b.organization_id,'import.execute') then raise exception 'import execution denied';end if;if b.status='completed' then return b;end if;if b.status<>'ready' then raise exception 'import batch is not ready';end if;
 update public.import_batches set status='importing',confirmed_by=auth.uid(),confirmed_at=now(),failure_reason=null where id=b.id;
 begin
  for i in select * from public.import_items where batch_id=b.id and reconciliation_status='ready' order by case target_type when'department'then 1 else 2 end,id loop
   prov:=jsonb_build_object('importBatchId',b.id,'sourceDigest',b.source_digest,'sourceType',b.source_type,'importedAt',now(),'importedBy',auth.uid(),'originalIdentifier',i.source_record_key,'classification','SAMPLE / UNAPPROVED','originalPayload',i.source_payload);
   person_name:=case i.target_type when'department'then i.source_payload->>'lead' when'task'then i.source_payload->>'owner' when'content_item'then i.source_payload->>'owner' when'sponsor'then i.source_payload->>'owner' when'decision'then i.source_payload->>'owner' else null end;mapped_member:=null;mapped_profile:=null;select pm.organization_member_id,om.profile_id into mapped_member,mapped_profile from public.import_person_mappings pm join public.organization_members om on om.id=pm.organization_member_id where pm.batch_id=b.id and pm.source_name=person_name and pm.mapping_status='mapped';
   if i.target_type='department' then insert into public.departments(organization_id,name,description,health,readiness,verification_status,metadata,import_batch_id,source_record_key,source_provenance)values(b.organization_id,i.source_payload->>'name',i.source_payload->>'description',i.source_payload->>'health',null,'sample_unapproved',jsonb_build_object('prototypeReadiness',i.source_payload->'progress','classification','SAMPLE / UNAPPROVED'),b.id,i.source_record_key,prov)returning id into target;if mapped_member is not null then insert into public.department_members(department_id,organization_member_id,title,is_lead)values(target,mapped_member,'Imported mapping — SAMPLE / UNAPPROVED',false)on conflict do nothing;end if;
   elsif i.target_type='task' then select target_id into target from public.import_items where batch_id=b.id and target_type='department' and source_record_key=i.mapping->>'departmentKey' and reconciliation_status='imported';if target is null then raise exception 'task department mapping unavailable';end if;insert into public.tasks(organization_id,department_id,title,status,priority,progress,due_at,created_by,updated_by,verification_status,visibility,import_batch_id,source_record_key,source_provenance)values(b.organization_id,target,i.source_payload->>'title',case lower(i.source_payload->>'status') when'done'then'completed' when'doing'then'in_progress' when'blocked'then'blocked' else'backlog'end,case lower(i.source_payload->>'priority') when'high'then'high' when'critical'then'critical' else'medium'end,coalesce((i.source_payload->>'progress')::smallint,0),null,auth.uid(),auth.uid(),'sample_unapproved','department',b.id,i.source_record_key,prov)returning id into target;if mapped_member is not null then insert into public.task_assignees(task_id,organization_member_id,assigned_by)values(target,mapped_member,auth.uid())on conflict do nothing;end if;
   elsif i.target_type='content_item' then insert into public.content_items(organization_id,title,platform,status,owner_id,scheduled_at,asset_url,verification_status,import_batch_id,source_record_key,source_provenance)values(b.organization_id,i.source_payload->>'title',coalesce(i.source_payload->>'platform','unknown'),lower(replace(coalesce(i.source_payload->>'status','idea'),' ','_')),mapped_profile,null,null,'sample_unapproved',b.id,i.source_record_key,prov)returning id into target;
   elsif i.target_type='sponsor' then insert into public.sponsors(organization_id,name,category,stage,owner_id,next_action,visibility,verification_status,import_batch_id,source_record_key,source_provenance)values(b.organization_id,i.source_payload->>'organization',i.source_payload->>'category','prospecting',mapped_profile,i.source_payload->>'nextAction','restricted','sample_unapproved',b.id,i.source_record_key,prov)returning id into target;
   elsif i.target_type='milestone' then insert into public.milestones(organization_id,title,description,workstream,status,due_at,verification_status,import_batch_id,source_record_key,source_provenance)values(b.organization_id,i.source_payload->>'title',i.source_payload->>'description',i.source_payload->>'stream','draft',null,'sample_unapproved',b.id,i.source_record_key,prov)returning id into target;
   elsif i.target_type='decision' then insert into public.decisions(organization_id,title,owner_id,description,impact,due_at,status,approval_required,visibility,proposed_by,requested_by,verification_status,import_batch_id,source_record_key,source_provenance)values(b.organization_id,i.source_payload->>'title',mapped_profile,'Imported prototype decision — SAMPLE / UNAPPROVED',i.source_payload->>'impact',null,'draft',false,'restricted',auth.uid(),auth.uid(),'sample_unapproved',b.id,i.source_record_key,prov)returning id into target;
   elsif i.target_type='resource' then insert into public.resources(organization_id,title,resource_type,url,description,owner_id,visibility,verification_status,import_batch_id,source_record_key,source_provenance)values(b.organization_id,i.source_payload->>'title',i.source_payload->>'type',null,i.source_payload->>'description',auth.uid(),'restricted','sample_unapproved',b.id,i.source_record_key,prov)returning id into target;
   else raise exception 'unsupported import target %',i.target_type;end if;
   update public.import_items set reconciliation_status='imported',target_id=target,updated_at=now() where id=i.id;counts:=jsonb_set(counts,array[i.target_type],to_jsonb(coalesce((counts->>i.target_type)::int,0)+1),true);
  end loop;
  update public.import_batches set status='completed',completed_at=now(),imported_counts=counts where id=b.id returning * into b;
 exception when others then update public.import_batches set status='rolled_back',failure_reason=sqlerrm,imported_counts='{}' where id=b.id returning * into b;end;return b;
end$$;

revoke all on function public.create_import_preview(uuid,text,text,text,text,jsonb,jsonb) from public;revoke all on function public.set_import_item_state(uuid,text,text) from public;revoke all on function public.set_import_person_mapping(uuid,text,uuid)from public;revoke all on function public.execute_import_batch(uuid) from public;
grant execute on function public.create_import_preview(uuid,text,text,text,text,jsonb,jsonb),public.set_import_item_state(uuid,text,text),public.set_import_person_mapping(uuid,text,uuid),public.execute_import_batch(uuid) to authenticated;
create or replace function public.audit_import_mutation()returns trigger language plpgsql security definer set search_path=public,pg_temp as $$declare org uuid:=coalesce(new.organization_id,old.organization_id);target uuid:=coalesce(new.id,old.id);row_data jsonb:=case when tg_op='DELETE'then to_jsonb(old)else to_jsonb(new)end;batch uuid;corr uuid;begin batch:=case when tg_table_name='import_batches'then target else(row_data->>'batch_id')::uuid end;corr:=coalesce(nullif(row_data->>'correlation_id','')::uuid,gen_random_uuid());insert into public.audit_events(organization_id,actor_type,actor_id,action,target_type,target_id,before_state,after_state,source,visibility,context,correlation_id)values(org,case when auth.uid()is null then'system'::public.actor_type else'human'::public.actor_type end,auth.uid(),'import.'||tg_table_name||'.'||lower(tg_op),tg_table_name,target,case when tg_op='INSERT'then null else to_jsonb(old)end,case when tg_op='DELETE'then null else to_jsonb(new)end,'database_trigger','restricted',jsonb_build_object('phase','2D','batchId',batch),corr);return case when tg_op='DELETE'then old else new end;end$$;
create trigger import_batches_audit after insert or update on public.import_batches for each row execute function public.audit_import_mutation();create trigger import_items_audit after insert or update on public.import_items for each row execute function public.audit_import_mutation();create trigger import_people_audit after insert or update on public.import_person_mappings for each row execute function public.audit_import_mutation();
